function [meas,species] = formatdata_NN_V1()
folderPathstr='F:\Matlab Data\formatdata\';
rmsPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\RMS\';
atrPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\ATR\';
amrPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\AMR\';
zcrPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\ZCR\';
SpeCPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Centroid\';
SpeRPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Rolloff\';
SpeFPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Flux\';
SpeEPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Entropy\';
AutoCorrPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\AutoCorr\';
RCEPSPathstr='C:\Users\Administrator\Desktop\android acoustic\analysis\RCEPS\';
rmsPath='C:\Users\Administrator\Desktop\android acoustic\analysis\RMS\*.txt';
atrPath='C:\Users\Administrator\Desktop\android acoustic\analysis\ATR\*.txt';
amrPath='C:\Users\Administrator\Desktop\android acoustic\analysis\AMR\*.txt';
zcrPath='C:\Users\Administrator\Desktop\android acoustic\analysis\ZCR\*.txt';
SpeCPath='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Centroid\*.txt';
SpeRPath='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Rolloff\*.txt';
SpeFPath='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Flux\*.txt';
SpeEPath='C:\Users\Administrator\Desktop\android acoustic\analysis\S_Entropy\*.txt';
AutoCorrPath='C:\Users\Administrator\Desktop\android acoustic\analysis\AutoCorr\*.txt';
RCEPSPath='C:\Users\Administrator\Desktop\android acoustic\analysis\RCEPS\*.txt';
fileListrms=dir(rmsPath);
fileListatr=dir(atrPath);
fileListamr=dir(amrPath);
fileListzcr=dir(zcrPath);
fileListSpeC=dir(SpeCPath);
fileListSpeF=dir(SpeFPath);
fileListSpeE=dir(SpeEPath);
fileListSpeR=dir(SpeRPath);
fileListAuto=dir(AutoCorrPath);
fileListRCEPS=dir(RCEPSPath);
fileNum=length(fileListSpeC);
formatdata=[];
meas = [];
species = [];
for i=1:fileNum
    %disp(i);
     Name=fileListSpeC(i).name;
     %disp(Name);
	 %disp(Name);
     splitName=strsplit(Name,'.');
     % fileName=strcat(rmsPathstr,Name);
     % rmsdata=dlmread(fileName);
    
%      Name=fileListatr(i).name;
%      fileName=strcat(atrPathstr,Name);
%      atrdata=dlmread(fileName);
%      ATRs = var(atrdata);
% 	 ATRm = mean(atrdata);
% 	 
%      
%      Name=fileListamr(i).name;
%      fileName=strcat(amrPathstr,Name);
%      amrdata=dlmread(fileName);
%       AMRs = var(amrdata);
%     AMRm = mean(amrdata);
% 	
%      Name=fileListzcr(i).name;
%      fileName=strcat(zcrPathstr,Name);
%      zcrdata=dlmread(fileName);
%      ZCRs = var(zcrdata);
% 	 ZCRm = mean(zcrdata);
	
     Name=fileListSpeC(i).name;
     fileName=strcat(SpeCPathstr,Name);
     SpeCdata=dlmread(fileName);
     SCs = var(SpeCdata);
     SCm = mean(SpeCdata);
	 SCSUM = sum(SpeCdata);
	 SCkurtosis = kurtosis(SpeCdata);
     SCskewness =  skewness(SpeCdata);
     SCmedian  = median(SpeCdata);
     SCrange = max(SpeCdata) - min(SpeCdata);
	 SCmode = mode(SpeCdata);
	 SCstd = std(SpeCdata);
	 SCtem = quantile(SpeCdata,3);
	 SCinterquartiles = SCtem(3)-SCtem(1);
	 SCcov = SCstd/SCm;
     
     Name=fileListSpeF(i).name;
     fileName=strcat(SpeFPathstr,Name);
     SpeFdata=dlmread(fileName);
     SFs = var(SpeFdata);
     SFm = mean(SpeFdata);
	 SFSUM = sum(SpeFdata);
	 SFkurtosis = kurtosis(SpeFdata);
     SFskewness =  skewness(SpeFdata);
     SFmedian  = median(SpeFdata);
     SFrange = max(SpeFdata) - min(SpeFdata);
	 SFmode = mode(SpeFdata);
	 SFstd = std(SpeFdata);
	 SFtem = quantile(SpeFdata,3);
	 SFinterquartiles = SFtem(3)-SFtem(1);
	 SFcov = SFstd/SFm;
     
     Name=fileListSpeE(i).name;
     fileName=strcat(SpeEPathstr,Name);
     SpeEdata=dlmread(fileName);
	  SEs = var(SpeEdata);
	  SEm = mean(SpeEdata);
	  SESUM = sum(SpeEdata);
      SEkurtosis = kurtosis(SpeEdata);
      SEskewness =  skewness(SpeEdata);
      SEmedian  = median(SpeEdata);
      SErange = max(SpeEdata) - min(SpeEdata);
	  SEmode = mode(SpeEdata);
	  SEstd = std(SpeEdata);
	  SEtem = quantile(SpeEdata,3);
	  SEinterquartiles = SEtem(3)-SEtem(1);
	  SEcov = SEstd/SEm;
     
     Name=fileListAuto(i).name;
     fileName=strcat(AutoCorrPathstr,Name);
     AutoCdata=dlmread(fileName);
     ACs = var(AutoCdata);
	 ACm = mean(AutoCdata);
	 ACSUM = sum(AutoCdata);
     ACkurtosis = kurtosis(AutoCdata);
     ACskewness =  skewness(AutoCdata);
     ACmedian  = median(AutoCdata);
     ACrange = max(AutoCdata) - min(AutoCdata);
     ACmode = mode(AutoCdata);
	 ACstd = std(AutoCdata);
	 ACtem = quantile(AutoCdata,3);
	 ACinterquartiles = ACtem(3)-ACtem(1);
	 ACcov = ACstd/ACm;
	 %Name=fileListRCEPS(i).name;
     %fileName=strcat(RCEPSPathstr,Name);
     %
    
     Name=fileListSpeR(i).name;
     fileName=strcat(SpeRPathstr,Name);
     SpeRdata=dlmread(fileName);
     SRs = var(SpeRdata);
	 SRm = mean(SpeRdata);
	 SRSUM = sum(SpeRdata);
     SRkurtosis = kurtosis(SpeRdata);
     SRskewness =  skewness(SpeRdata);
     SRmedian  = median(SpeRdata);
     SRrange = max(SpeRdata) - min(SpeRdata);
     SRmode = mode(SpeRdata);
	 SRstd = std(SpeRdata);
	 SRtem = quantile(SpeRdata,3);
	 SRinterquartiles = SRtem(3)-SRtem(1);
	 SRcov = SRstd/SRm;
	 
    labelS = splitName{1}(1:1);
	labelN = str2num(labelS);
    %formatdata ={atrdata,amrdata,zcrdata,SpeCdata,SpeFdata,SpeEdata,SpeRdata,labelS};
	%formatdata =[SCs,SCSUM,SCkurtosis,SCmedian,SCstd,SCinterquartiles,SFrange,SESUM,SErange,SEcov,ACs,ACm,ACmode,SRSUM,SRskewness];
    formatdata =[ACSUM,ACs,ACm,SFm,SFSUM,SFs,SEm,SEs,SCSUM];
	%formatdata =[ACSUM,ACs,ACm,ACkurtosis,ACskewness,SFm,SFSUM,SFs,SFkurtosis,SFskewness,SEm,SEs,SEkurtosis,SEskewness,SCSUM,SCkurtosis,SCskewness];
    %formatdata =[ACkurtosis,ACskewness,ACmedian,ACrange,SFkurtosis,SFskewness,SEkurtosis,SFmedian,SFrange,SEskewness,SEmedian,SErange,SCkurtosis,SCskewness,SCmedian,SCrange,SRkurtosis,SRskewness,SRmedian,SRrange];
   % formatdata =[ACs,ACm,ACSUM,ACkurtosis,ACskewness,ACmedian,ACrange,ACmode,ACstd,ACinterquartiles,ACcov,SCs,SCm,SCSUM,SCkurtosis,SCskewness,SCmedian,SCrange,SCmode,SCstd,SCinterquartiles,SCcov,SFs,SFm,SFSUM,SFkurtosis,SFskewness,SFmedian,SFrange,SFmode,SFstd,SFinterquartiles,SFcov,SEs,SEm,SESUM,SEkurtosis,SEskewness,SEmedian,SErange,SEmode,SEstd,SEinterquartiles,SEcov,SRs,SRm,SRSUM,SRkurtosis,SRskewness,SRmedian,SRrange,SRmode,SRstd,SRinterquartiles,SRcov];
    meas=[meas;formatdata];
    species = [species;labelS];
end
